### ISSUE TITLE
build

### ISSUE THREAD

**Issue by ghost** [perkinslr/OpenComputersX86#2]
how do i compile a mod from git? please help.

**Comment by Techokami** [comment]
You currently can't do so very easily, as the build scripts are missing.

**Comment by perkinslr** [comment]
I wouldn't recommend trying to build this unless you want to work on getting it working.  It currently hangs on boot most of the time.  If you do want to build it, start by building opencomputers, then you can list the source for this and JPC as additional sources in OC's build.gradle, which will let you produce a modified version of OC which includes this.  Eventually I'll provide separate build scripts for this, but until I have it actually working, it's not a high priority.
